name: Build Vue
on: [push]
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vue App to GitHub Pages
        uses: dencee/VuePagesAction@main
